# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33ce072809754b85945e3a2c8a291d4812b5847bb9960a84e74b0e0b1b2bcd1f66221b0febfbc642e0ac870745d8feb05e9fc6b1768732ece3abeebef7d3857c

test:
  secret_key_base: 5c50636157642d3cd5439647e34bc510a0b19960f157e3425cb6ecedff59c859d2a782fbfbacc133653c0d07cafa2d23651eaf55cf45c5441149e03e4000ec33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
